version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`aswwcsckkcoskkg4gs4cgckk.186.249.193.124.sslip.io`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=4000"